apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportofolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myportofolio
        image: koubelan/myportofolio:latest
        ports:
        - containerPort: 5000
