name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Decode GCP service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        
    - name: echo GCP service account key
      run: cat gcp-key.json
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myportofolio:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode GCP service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        
      - name: Export GCP service account key
        run: |
          echo "SA_KEY=$(jq -c . < gcp-key.json)" >> $GITHUB_ENV

      - name: test
        run: echo ${{ env.SA_KEY }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.SA_KEY }}

       # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: myportofolio-cluster
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          location: us-central1


      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
