name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Decode GCP service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        
    - name: echo GCP service account key
      run: echo gcp-key.json
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myportofolio:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode GCP service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        
      - name: echo GCP service account key
        run: echo gcp-key.json

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: "${HOME}/gcp-key.json"
          export_default_credentials: true

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"

      - name: Verify gcloud authentication
        run: |
          gcloud auth list
          gcloud config list

       # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: myportofolio-cluster
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          location: us-central1


      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
